### ISSUE TITLE
Unable to go to dimension

### ISSUE THREAD

**Issue by Protheus** [Darkhax-Minecraft/Hunting-Dimension#1] opened 2017-12-10 22:58 UTC
HuntingDimension-1.12.2-1.0.1
Bookshelf-1.12.2-2.3.509
Forge: 2561
Default settings config (nothing changed) - dim: 28885

1. Created the portal (within a chunk)
2. Used my Emerald sword to activate portal
3. Stood in middle of portal and sneak.. nothing happened

- Broken the portal and redo and still unable to go to portal
- Reloaded the game, nothing

**Ruins_log_dim_28885.txt:**
Loading options from: C:\Users\xxxx\AppData\Roaming\.minecraft\saves\PlayGround\DIM28885
tries_per_chunk_normal = 6
chance_to_spawn_normal = 10.0
templateInstancesMinDistance = 256.0
anyRuinsMinDistance = 64.0
Ruins mod loaded successfully for world C:\Users\xxxx\AppData\Roaming\.minecraft\saves\PlayGround\DIM28885, template files: 31

**Images:**
![2017-12-10_23 45 50](https://user-images.githubusercontent.com/1455178/33810443-e17f2f58-de04-11e7-9098-db8e6737e96d.png)
![2017-12-10_23 45 56](https://user-images.githubusercontent.com/1455178/33810444-e1971794-de04-11e7-8de8-4cd8959c3d48.png)

**Comment by Darkhax** [comment] 2017-12-11 01:51
Thanks for making this report. I am not able to reproduce this issue in my testing world, or on my personal mod pack. I believe this is an issue with another mod somehow interfering. For example I have a mod called [Dimension Stages](https://minecraft.curseforge.com/projects/dimension-stages) which can prevent access to a dimension based on modpack configs. Could I get a copy of your mod list? Also are you playing on a server?

**Comment by Protheus** [comment] 2017-12-11 10:44
- https://pastebin.com/rsHHnzSU
- Single, laptop, no server.

**Comment by Darkhax** [comment] 2017-12-13 20:12
Sorry for the delay. I have just released a new update that will add some debug information to help track down your issue. In the new update when you try to go through the portal you will likely get a message saying that another mod is preventing access to the portal. If you look in the console, there should be a message with more information to help track down which mod is actually causing the issue.

**Comment by Protheus** [comment] 2017-12-13 20:17
trying it out now

edit: No error in the console/log

**Comment by Darkhax** [comment] 2017-12-14 19:19
It didn't even give you a chat message? That's extremely odd. Is there any way I could download the modpack instance for further testing?

**Comment by Protheus** [comment] 2017-12-14 21:05
How can I message you with the link.. it is going to be a wetransfer (205mb).

edit: nevermind, found your email, you will have an email from me
edit: file send and you should have it. goodluck and thank you

**Comment by Darkhax** [comment] 2017-12-14 21:22
Thanks for sending the file. Testing it out now.

**Comment by Darkhax** [comment] 2017-12-14 21:34
Okay, so I can reproduce this issue you're having! Thanks for sending me the files, I will keep this issue updated as I dig into it.

**Comment by Protheus** [comment] 2017-12-14 21:45
That is quick :) 

Take your time, you have other mods that i need to play with 😀

**Comment by Darkhax** [comment] 2017-12-14 23:46
Okay, I have worked out the issue. The [Universal Remote](https://minecraft.curseforge.com/projects/universal-remote) mod is replacing the player entity with their own entity class. This is a very bad thing for them to do, because it causes all players to fail the fake player test. This is going to have many issues across all of my mods, and several other mods, I think the CoFH mods have a similar check.

**Comment by Darkhax** [comment] 2017-12-15 00:02
I've opened an issue on their repo, which you can find [here](https://github.com/orbwoi/UniversalRemote/issues/21).

**Comment by Protheus** [comment] 2017-12-15 07:32
if it is related to another mod, you can close this one and I will track the other git. Thank you for this

**Comment by Darkhax** [comment] 2017-12-19 05:32
After talking with the dev of the universal remote, I have changed my code in bookshelf to be a bit more lenient. If no major issues arise, this should be fixed. Just update to [2.3.512](https://minecraft.curseforge.com/projects/bookshelf/files/2511546) or newer.

**Closed as completed by Darkhax** 2017-12-19 05:32 UTC

**Comment by Protheus** [comment] 2017-12-19 19:43
Thank you. Will check it out

**Comment by vanchelot** [comment] 2018-01-12 00:20
Hello.

I'm having the same problem. I'm using latest Bookshelf and Hunting Dimension. When I try to use the portal, the chat says: 

"You are an invalid entity, and can not travel through the portal!"

**Comment by Darkhax** [comment] 2018-01-12 00:33
Hello @vanchelot Are you using the universal remote mod as well? That mod is currently incompatible with many mods due to how they do the player check. If you're not using that mod, could you upload a log file of the game after you try to go through the portal?

**Comment by vanchelot** [comment] 2018-01-12 01:40
I'm no using universal remote mod.

I think this is the info you're looking for:

[0111/203035:INFO:GameCallbacks.cpp(178)] game/game () info [20:30:35] [main/INFO]: [CHAT] You are an invalid entity, and can not travel through the portal!

[0111/203035:INFO:GameCallbacks.cpp(178)] game/game () info [20:30:35] [Server thread/INFO] [Hunting Dimension]: Could not teleport Vanchelot because they are an invalid player entity! Class is class com.mrnobody.morecommands.patch.PatchEntityPlayerMP$EntityPlayerMP

**Comment by vanchelot** [comment] 2018-01-12 01:55
Removed the mod mentioned in the log fragment. Then I used the portal and it worked!

I won't use that mod a lot so it's fine for now.

If it helps, for you or anyone who reads this, the mod I was using and was causing the problem is MoreCommands v6.0. The mod site is:

http://morecommands.bplaced.net/index.php

And the source of the mod is in here:

https://github.com/MrNobody98/morecommands

Thanks a lot for your help.

**Comment by Darkhax** [comment] 2018-01-12 03:35
Thank you for looking into the issue further.

**Comment by iBattery355** [comment] 2018-02-01 15:58
I have the same entity problem. The log:

- Could not teleport iBattery because they are an invalid player entity! Class is class micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP

- [CHAT] You are an invalid entity, and can not travel through the portal!

It is seemed that it is not compatible with the galacticraft now.

**Comment by vanchelot** [comment] 2018-02-01 17:16
Awww man :(  I can confirm iBattery findings. 


- [12:12:58] [Server thread/INFO] [Hunting Dimension]: Could not teleport Vanchelot because they are an invalid player entity! Class is class micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP

**Comment by Darkhax** [comment] 2018-02-01 20:21
Unfortunately this change in Galacticraft makes it incompatible with many other mods and not just this one. I know the unreleased SevTech pack has both mods working together so I will ask Darkosto about it.

**Comment by iBattery355** [comment] 2018-02-02 00:19
Thank you for telling the info. Hope this could be fixed in the future.

**Comment by Darkhax** [comment] 2018-02-02 01:11
@iBattery355 @vanchelot The API they used to fix it was [Player API](https://minecraft.curseforge.com/projects/player-api). I am going to look into fixing this on my end further as well, however it is very frustrating when people are writing hacky code like this.

**Comment by Sanguinelord94** [comment] 2021-09-23 05:04
Hey @Darkhax has this issue been resolved? running a server on SevTech Ages of the Sky with same issue coming up with using latest Bookshelf.
